GEMINI_MODEL = "gemini-2.0-flash"
ABHIRUCHI_GULHANE = "Abhiruchi Gulhane"
NISHANT_MODI = "Nishant Modi"
NICOLAY_HILARION = "Nicolay Hilarion"
JULIO_HERRERA = "Julio Herrera"
NAVEEN_KODURI = "Koduri, Naveen"
JJ = "Betancur Correa, jhaider"
LIST_OF_NAMES = [NISHANT_MODI, ABHIRUCHI_GULHANE, NICOLAY_HILARION, NAVEEN_KODURI, JULIO_HERRERA, JJ]
