GEMINI_MODEL = "gemini-2.5-flash"
ABHIRUCHI_GULHANE = "Gulhane, Abhiruchi"
NISHANT_MODI = "Modi, Nishant"
NICOLAY_HILARION = "Hilarion, Nicolay"
JULIO_HERRERA = "Herrera, Julio"
NAVEEN_KODURI = "Koduri, Naveen"
JJ = "Betancur Correa, jhaider"
AGAM_THIND = "Thind, Agam"
LIST_OF_NAMES = [NISHANT_MODI, ABHIRUCHI_GULHANE, NICOLAY_HILARION, NAVEEN_KODURI, JULIO_HERRERA, JJ, AGAM_THIND]
