-- Create tables for Society Finance Tracker

-- 1. Flats Table
CREATE TABLE IF NOT EXISTS flats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    flat_no TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    mobile TEXT,
    email TEXT,
    maintenance_amount DECIMAL(12, 2) DEFAULT 4500.00,
    status TEXT DEFAULT 'Active'
);

-- 2. Vendors Table
CREATE TABLE IF NOT EXISTS vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    vendor_name TEXT NOT NULL,
    category TEXT,
    contact TEXT,
    payment_mode TEXT,
    notes TEXT
);

-- 3. Maintenance Billing Table
CREATE TABLE IF NOT EXISTS billing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    month TEXT NOT NULL,
    flat_no TEXT NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    invoice_no TEXT,
    status TEXT DEFAULT 'Unpaid'
);

-- 4. Receipts Table
CREATE TABLE IF NOT EXISTS receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    entry_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    flat_no TEXT NOT NULL,
    month TEXT NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    mode TEXT NOT NULL,
    ref_no TEXT,
    drive_link TEXT,
    notes TEXT,
    entered_by TEXT
);

-- 5. Expenses Table
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    entry_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    vendor TEXT NOT NULL,
    category TEXT NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    mode TEXT NOT NULL,
    ref_no TEXT,
    drive_link TEXT,
    notes TEXT,
    paid_by TEXT DEFAULT 'Society',
    approved_by TEXT DEFAULT 'Chairman'
);

-- 6. Reimbursements Table
CREATE TABLE IF NOT EXISTS reimbursements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    entry_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    member_name TEXT NOT NULL,
    related_expense_entry TEXT,
    amount DECIMAL(12, 2) NOT NULL,
    drive_link TEXT,
    notes TEXT,
    status TEXT DEFAULT 'Pending'
);

-- 7. Petty Cash Table
CREATE TABLE IF NOT EXISTS petty_cash (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    voucher_no TEXT,
    description TEXT,
    debit DECIMAL(12, 2) DEFAULT 0,
    credit DECIMAL(12, 2) DEFAULT 0,
    drive_link TEXT,
    notes TEXT,
    paid_to TEXT
);

-- 8. Bank Ledger Table
CREATE TABLE IF NOT EXISTS bank_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    description TEXT,
    debit DECIMAL(12, 2) DEFAULT 0,
    credit DECIMAL(12, 2) DEFAULT 0,
    notes TEXT,
    ref_type TEXT,
    ref_entry TEXT
);

-- Enable Row Level Security (optional but recommended)
-- For now, we'll keep it simple and assume public access if the anon key is used correctly.
-- In a real app, you'd add policies here.
